CHARGE_BIN_SIZE = 0.05
DISTANCE_BIN_SIZE = 0.1

CHARGE_LOWER_LIMIT = -2
CHARGE_UPPER_LIMIT = 2
DISTANCE_UPPER_LIMIT = 10
TOPO_DIST_UPPER_LIMIT = 10

NUM_CHARGE_BUCKET = int((CHARGE_UPPER_LIMIT - CHARGE_LOWER_LIMIT) / CHARGE_BIN_SIZE + 1)
NUM_DISTANCE_BUCKET = int(DISTANCE_UPPER_LIMIT / DISTANCE_BIN_SIZE + 1)